// Custom root HTML document for the Expo Web static export.
// This wraps every statically-rendered route. We use it to inject the PWA
// manifest / meta tags and to register the service worker.
//
// NOTE: the inline service-worker registration script is allowed by the API's
// CSP because `scriptSrc` includes `'unsafe-inline'` (see apps/api/src/index.ts).
import { ScrollViewStyleReset } from "expo-router/html";
import { type PropsWithChildren } from "react";

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"
        />

        {/* PWA */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0D9488" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Orbit" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />

        {/* Disable body scrolling on web so ScrollView components work correctly. */}
        <ScrollViewStyleReset />

        {/* Register the service worker generated by Workbox at build time. */}
        <script dangerouslySetInnerHTML={{ __html: registerServiceWorker }} />
      </head>
      <body>{children}</body>
    </html>
  );
}

const registerServiceWorker = `
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/sw.js').catch(function (err) {
      console.error('Service worker registration failed:', err);
    });
  });
}
`;
